# Generated by Django 4.1.2 on 2022-10-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('kms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('cilindrada', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='familiar',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
